// neoproto currently only supports proto2 syntax
syntax = "proto2";

// This is an example protobuf file to demonstrate the capabilities of the library. It includes various features such as nested messages, enums, oneof fields, and comments for documentation purposes.
package MyApi.V1;

/**
 * Metadata shared across multiple message types.
 */
message MyNestedMessage {
  optional int32 id = 1;
  optional int64 some_other_long = 2;
}

/**
 * Request message for the MyMessage service.
 * MessageId: 1
 * client to provider
 */
message MyMessageReq {
  optional string value = 1;
  optional int64 some_long = 2;
  // This field needs some additional explanation.
  optional MyNestedMessage nested = 3;
  optional bool some_thing = 4;
  
  repeated string some_repeated_strings = 5;
  repeated MyNestedMessage some_repeated_nested = 6;
}

/**
 * Response message containing the result of a MyMessageReq.
 * MessageID 2
 * Directionality: provider-to-client
 */
message MyMessageRes {
  optional string value = 1;
  optional int64 some_long = 2;
  optional MyNestedMessage nested = 3;
  optional bool some_thing = 4;
  
  repeated string some_repeated_strings = 5;
  repeated MyNestedMessage some_repeated_nested = 6;
  optional bytes binary_data = 7;
}

/**
 * An important notification of some change.
 * MessageID: 3
 * Directionality: bidirectional
 */
message SomethingElseNotification {
  optional string name = 1;
  optional int32 id = 2;
}
