import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { runProtobufjsCli } from "./pbcli.js";
import { createNamespaceSerializers } from "./generators/serialization.js";
import { createRootNamespaceTypes } from "./generators/types.js";
import { createNamespaceTraits } from "./generators/traits.js";
import { createRootNamespaceWrappers } from "./generators/wrap.js";
import { createRootNamespaceUnwrappers } from "./generators/unwrap.js";
import { createNamespaceDocumentation } from "./generators/documentation.js";
import { associateMessages, isTopLevelMessage } from "./utils/associations.js";
import { findApiNamespace, getMessages } from "./utils/protobuf.js";
import {
  clearErrorState,
  getHasLoggedError,
  logError,
} from "./utils/logger.js";
import prettier from "prettier";
import { generateNamespaceTests } from "./generators/test.js";
import { executeCommand, getRelativePath } from "./utils/system.js";
import process from "node:process";

/**
 * Formats all .ts files in the specified directory using Prettier.
 * @param directory - The directory containing the .ts files to format.
 * @returns A promise that resolves when all files have been formatted.
 */
async function runPrettier(directory: string) {
  const tsFiles = await readdir(directory);
  const tsFilePaths = tsFiles
    .filter((file) => file.endsWith(".ts"))
    .map((file) => `${directory}/${file}`);

  for (const filePath of tsFilePaths) {
    const input = await readFile(filePath, "utf-8");
    const output = await prettier.format(input, { parser: "typescript" });
    await writeFile(filePath, output);
    console.log(`Formatted ${filePath} with Prettier`);
  }
}

function prependHeader(content: string, style: "ts" | "md" = "ts") {
  const lines = [
    "This file was auto-generated by neoproto tool.",
    "Do not edit this file directly. Instead, edit the source .proto file and regenerate.",
  ]
  if (style === "md") {
    return `<!--
${lines.join("\n")}
-->

${content}
`;
  }
  return `/**
  * ${lines.join("\n  * ")}
  */

${content}`;
}

/**
 * Options needed to run the main function of the CLI tool.
 */
interface Options {
  /** The output directory where generated files will be saved. */
  outDir: string;

  /** The path to the .proto file to process. */
  protoPath: string;
  
  /** The path to create the markdown documentation file. Defaults to README.md inside outDir. */
  docPath?: string;

  /** The output directory where test files will be saved. */
  testDir?: string;

  /** Whether to forcibly overwrite existing output directories. */
  flagForce?: boolean;

  /** Whether to skip formatting generated files with Prettier. */
  flagNoPrettier?: boolean;

  /** Whether to skip executing generated tests after generation. */
  flagNoTestExecution?: boolean;

  /** Whether to generate code that outputs verbose logging at runtime. */
  flagVerbose?: boolean;
}

/**
 * The main function that orchestrates the generation of serialization functions, traits, types, and tests based on a .proto file.
 * @param options - An object containing the necessary options to run the function, including output directory, .proto file path, test directory, and flags for force and Prettier.
 * @returns A promise that resolves when all tasks are completed, or rejects if any errors occur during the process.
 * @throws If the output directory or test directory already exists and the --force flag is not provided, the function will log an error and exit the process.
 */
async function run({
  docPath,
  outDir,
  protoPath,
  testDir,
  flagForce,
  flagNoPrettier,
  flagNoTestExecution,
  flagVerbose,
}: Options) {
  clearErrorState();

  if (existsSync(outDir)) {
    if (!flagForce) {
      logError(
        `Output directory ${outDir} already exists. Use --force or -f to overwrite.`,
      );
      return { error: true };
    }
    await rm(outDir, { force: true, recursive: true });
  }
  await mkdir(`${outDir}/protobuf`, { recursive: true });

  if (testDir && existsSync(testDir)) {
    if (!flagForce) {
      logError(
        `Test directory ${testDir} already exists. Use --force or -f to overwrite.`,
      );
      return { error: true };
    }
    await rm(testDir, { force: true, recursive: true });
  }

  const { namespace } = await runProtobufjsCli(protoPath, `${outDir}/protobuf`);
  const nsResult = findApiNamespace(namespace);
  if (!nsResult) {
    logError(
      `No namespace matching the API versioning pattern was found in ${protoPath}. Ensure that your .proto file contains a namespace that follows the format "NamespaceV1" (e.g., "MyApiV1", "my_api.v1", or "MyApi.V2").`,
      "",
    );
    return { error: true };
  }
  const { baseName, namespace: apiNamespace, version } = nsResult;
  console.log(`Found API namespace: ${apiNamespace.fullName} (Base Name: ${baseName}, Version: ${version})`);
  const topLevelMessages = getMessages(apiNamespace).filter(isTopLevelMessage);
  const associations = associateMessages(topLevelMessages);

  const apiName = baseName.split(".").filter(Boolean)[0] || baseName;

  await writeFile(
    `${outDir}/serialization.ts`,
    prependHeader(createNamespaceSerializers(apiNamespace.fullName, topLevelMessages)),
  );
  console.log(`Wrote serialization functions to ${outDir}/serialization.ts`);

  await writeFile(`${outDir}/wrap.ts`, prependHeader(createRootNamespaceWrappers(apiNamespace)));
  console.log(`Wrote wrapping functions to ${outDir}/wrap.ts`);

  await writeFile(
    `${outDir}/unwrap.ts`,
    prependHeader(createRootNamespaceUnwrappers({ namespace, generateVerbose: flagVerbose })),
  );
  console.log(`Wrote unwrapping functions to ${outDir}/unwrap.ts`);

  await writeFile(`${outDir}/types.ts`, prependHeader(createRootNamespaceTypes(apiNamespace)));
  console.log(`Wrote wrapped TypeScript interfaces to ${outDir}/types.ts`);

  await writeFile(
    `${outDir}/traits.ts`,
    prependHeader(createNamespaceTraits({
      apiName,
      apiVersion: version,
      namespace: apiNamespace,
      associations,
    })),
  );
  console.log(`Wrote traits to ${outDir}/traits.ts`);

  await writeFile(
    `${outDir}/index.ts`,
    prependHeader(`export * from "./serialization.js";
export * from "./traits.js";
export * from "./types.js";
export * from "./unwrap.js";
export * from "./wrap.js";
`,
    ));
  console.log(`Wrote index file to ${outDir}/index.ts`);

  const readmePath = docPath || `${outDir}/README.md`;
  if (!flagForce && existsSync(readmePath)) {
    logError(
      `Documentation file ${readmePath} already exists. Use --force or -f to overwrite.`,
    );
    return { error: true };
  }
  await writeFile(readmePath, prependHeader(createNamespaceDocumentation(
    {
      apiName,
      apiVersion: version,
      protoSource: await readFile(protoPath, "utf-8"),
      associations,
      topLevelMessages,
    }
  ), "md"));
  console.log(`Wrote markdown documentation to ${readmePath}`);

  if (testDir) {
    await mkdir(testDir, { recursive: true });
    await writeFile(
      `${testDir}/serialization.spec.ts`,
      prependHeader(generateNamespaceTests({
        apiName,
        topLevelMessages,
        relativePath: getRelativePath(testDir, outDir)
      })),
    );
    console.log(`Wrote unit test file to ${testDir}/serialization.spec.ts`);

    if (testDir !== outDir && !flagNoPrettier) await runPrettier(testDir);
  }

  if (!flagNoPrettier) await runPrettier(outDir);

  if (!flagNoTestExecution && testDir) {
    console.log("\nRunning generated tests...\n");
    try {
      await executeCommand(
        process.argv[0] || "node",
        ["--import", "tsx", "--test", `${testDir}/serialization.spec.ts`],
        process.cwd(),
      );
    } catch (err) {
      logError("Generated unit tests failed.", "");
    }
  }

  const error = getHasLoggedError();
  clearErrorState();
  return { error };
}

export { run };
