name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Level: patch, minor, or major'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version_type }} -m "chore: bump version to %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: npm ci

      - run: npm run build

      - run: npm test

      - name: Push Changes
        run: git push origin ${{ github.ref_name }} --follow-tags

      - name: Create GitHub Release
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: | # javascript
            const version = 'v${{ steps.bump_version.outputs.VERSION }}';
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              name: version,
              generate_release_notes: true,
            });

      - run: npm publish
